In [0]:
from google.colab import drive


In [2]:
drive.mount("/content/drive")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
%cd /content/drive/My Drive/Cifar10_colab


/content/drive/My Drive/Cifar10_colab


In [0]:
import cifar10

In [0]:
cifar10.data_path = "data/CIFAR-10/"

In [6]:
cifar10.maybe_download_and_extract()

Data has apparently already been downloaded and unpacked.


In [7]:
class_names = cifar10.load_class_names()
class_names

Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta


['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [8]:
images_train, cls_train, labels_train = cifar10.load_training_data()
images_test, cls_test, labels_test = cifar10.load_test_data()
images_train.shape,images_test.shape,cls_train.shape,labels_train.shape

Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch


((50000, 32, 32, 3), (10000, 32, 32, 3), (50000,), (50000, 10))

In [9]:
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split 
images_train_data = images_train.reshape(50000, 3072)
images_test_data = images_test.reshape(10000,3072)
#x_images_train, x_images_test, y_images_train, y_images_test = train_test_split(images_train_data, cls_train, random_state = 1)
pca_cifar = PCA()
pca_cifar.fit(images_train_data)
k =0 
total =0
while total < 0.95:
    total += pca_cifar.explained_variance_ratio_[k]
    k += 1
k

217

In [0]:
pca = PCA(n_components = k, whiten = True)
pca.fit(images_train_data)
x_train_reduced = pca.transform(images_train_data)
x_test_reduced = pca.transform(images_test_data)

In [11]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(x_train_reduced, cls_train)

y_pred=clf.predict(x_test_reduced)

#clf.score(x_test_reduced,y)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [22]:
clf.score(x_test_reduced,cls_test)

KeyboardInterrupt: ignored

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)


NameError: ignored

In [0]:
#from sklearn.metrics import confusion_matrix
#from sklearn.metrics import classification_report
#print(confusion_matrix(images_test_data,y_pred))
#print(classification_report(images_test_data,y_pred))

In [13]:
import pandas as pd
#Y = pd.read_csv("C:\\Users\\vinod\\Downloads\\y_pred.csv",header=None)
Y=y_pred
label_encoder1 = LabelEncoder()
integer_encoded1 = label_encoder1.fit_transform(Y)
integer_encoded1 = integer_encoded1.reshape(len(integer_encoded1), 1)
print(integer_encoded1)

[[3]
 [8]
 [8]
 ...
 [5]
 [5]
 [4]]


In [0]:
import numpy as np

In [0]:
import tensorflow as tf

In [20]:
data =['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
values = np.array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded1)
print(onehot_encoded)
print(onehot_encoded.shape[0])
# invert first example
list_y=[]
for i in range(onehot_encoded.shape[0]):
    inverted = label_encoder.inverse_transform([np.argmax(onehot_encoded[i, :])])
    #print(type(inverted))
    list_y.append(inverted)
    

df=pd.DataFrame(list_y)
df

['airplane' 'automobile' 'bird' 'cat' 'deer' 'dog' 'frog' 'horse' 'ship'
 'truck']
[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
10000


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


0
0            cat
1           ship
2           ship
3       airplane
4           frog
5           frog
6     automobile
7           frog
8            cat
9     automobile
10          ship
11         truck
12          bird
13         horse
14         truck
15          ship
16           dog
17         horse
18          ship
19          frog
20         horse
21      airplane
22      airplane
23         truck
24          deer
25          frog
26           cat
27      airplane
28         truck
29          frog
...          ...
9970        bird
9971       truck
9972        frog
9973        ship
9974  automobile
9975       horse
9976        bird
9977        frog
9978        deer
9979         cat
9980    airplane
9981        deer
9982       horse
9983  automobile
9984        deer
9985       truck
9986        ship
9987        ship
9988        ship
9989        deer
9990       horse
9991       truck
9992         cat
9993         cat
9994         cat
9995         cat
9996         dog
9997         dog
9998         dog
9999        deer

[10000 rows x 1 columns]

In [0]:
import numpy as np
np.savetxt('y_pred_final.csv',df,fmt="%s")