In [1]:
import cifar10
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [2]:
cifar10.data_path = "data/CIFAR-10/"

In [3]:
cifar10.maybe_download_and_extract()

Data has apparently already been downloaded and unpacked.


In [4]:
class_names = cifar10.load_class_names()
class_names

Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta


['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [5]:
images_train, cls_train, labels_train = cifar10.load_training_data()
images_test, cls_test, labels_test = cifar10.load_test_data()

Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch


In [6]:
images_train_data = images_train.reshape(50000, 3072)

In [7]:
x_images_train, x_images_test, y_images_train, y_images_test = train_test_split(images_train_data, cls_train, random_state = 1)

In [8]:
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

In [11]:
pca_cifar = PCA()
pca_cifar.fit(x_images_train)
k =0 
total =0
while total < 0.95:
    total += pca_cifar.explained_variance_ratio_[k]
    k += 1
k

216

In [12]:
pca = PCA(n_components = k, whiten = True)
pca.fit(x_images_train)
x_train_reduced = pca.transform(x_images_train)
x_test_reduced = pca.transform(x_images_test)

In [13]:
%%time
rf = KNeighborsClassifier(n_neighbors = 3, algorithm = 'kd_tree')
rf.fit(x_train_reduced, y_images_train)
y_pca_pred = rf.predict(x_test_reduced)

Wall time: 4min 56s


In [14]:
print(confusion_matrix(y_images_test, y_pca_pred))
print(classification_report(y_images_test, y_pca_pred))

[[567   1 145  15  90   5   5   0 409   0]
 [312  93 184  54 225   5  16   2 355   0]
 [249   0 435  50 408   2  19   1 128   0]
 [272   1 354 134 274  15  22   1 180   0]
 [231   0 226  49 594   3   7   2 137   0]
 [276   1 394 110 280  33  22   0 117   0]
 [186   1 296  70 487   5  91   3 104   0]
 [251   2 305  64 440   6  29  58 101   0]
 [259   3  98  22  67   3   6   2 775   0]
 [293   9 232  56 248  12  12   0 386   8]]
             precision    recall  f1-score   support

          0       0.20      0.46      0.27      1237
          1       0.84      0.07      0.14      1246
          2       0.16      0.34      0.22      1292
          3       0.21      0.11      0.14      1253
          4       0.19      0.48      0.27      1249
          5       0.37      0.03      0.05      1233
          6       0.40      0.07      0.12      1243
          7       0.84      0.05      0.09      1256
          8       0.29      0.63      0.39      1235
          9       1.00      0.01      